language: python
python:
  - "3.8"

services:
  - postgresql

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test
  
before_script:
  - psql -c 'create database test;' -U postgres

# command to install dependencies
install: "pip3 install -r requirements.txt"

# command to run tests
jobs:
  include:
    - stage: Test
      name: TDD
      before_script:
        - psql -c 'create database test;' -U postgres
      script: nosetests

    - stage: Test
      name: BDD
      addons:
        chrome: stable
        apt:
          packages:
            - chromium-chromedriver 
            - python3-selenium
      before_script:
        - chromedriver --version
        # update chromedriver to the latest version, otherwise it would not be compatible with Chrome v92
        - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
        - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
        - unzip chromedriver_linux64.zip -d ~/bin
        - psql -c 'create database test;' -U postgres
        - gunicorn --log-level=critical --bind=127.0.0.1:8080 service:app &  # start a Web server in the background
        - sleep 5 # give Web server some time to bind to sockets, etc
        - curl -I http://localhost:8080/  # make sure the service is up
      script:
        - behave

after_success:
 - codecov
